# Generated by Django 5.0.4 on 2024-05-06 14:04

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state_province', models.CharField(max_length=255, verbose_name='state/province')),
                ('property_type', models.CharField(choices=[('Single family home', 'Single family home'), ('Townhouse', 'Townhouse'), ('Condominium', 'Condominium'), ('Apartment', 'Apartment'), ('Office building', 'Office building'), ('Retail space', 'Retail space'), ('Industrial property', 'Industrial property'), ('Land', 'Land')], max_length=255, verbose_name='property type')),
                ('postal_code', models.CharField(max_length=255, verbose_name='zip/postal code')),
                ('square_footage', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='square footage(in meter squared)')),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('year_built', models.CharField(max_length=4)),
                ('description', models.TextField()),
                ('price', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('active', 'active'), ('pending', 'pending'), ('sold', 'sold')])),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326)),
            ],
        ),
    ]
