# Generated by Django 5.0.4 on 2024-05-09 16:19

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_amenities_property_image_property_title_listing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenities',
            options={'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(9.005401, 38.763611), geography=True, srid=4326),
        ),
    ]
