# Generated by Django 5.0.4 on 2024-05-15 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_agentrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentrating',
            name='user',
        ),
    ]
