# Generated by Django 5.0.4 on 2024-05-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_agentrating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrating',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
