# Generated by Django 5.0.4 on 2024-05-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_agentrating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrating',
            name='average_rating',
            field=models.IntegerField(default=0.0),
        ),
    ]
