# Generated by Django 5.0.4 on 2024-05-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_agentrating_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrating',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
